version: '3.8'

services:
  # --- WORKER SERVERS ---
  server-1:
    build: .
    container_name: server-1
    command: python server.py 8000
    ports:
      - "8001:8000"  # Map laptop 8001 -> container 8000

  server-2:
    build: .
    container_name: server-2
    command: python server.py 8000
    ports:
      - "8002:8000"

  server-3:
    build: .
    container_name: server-3
    command: python server.py 8000
    ports:
      - "8003:8000"

  server-4:
    build: .
    container_name: server-4
    command: python server.py 8000
    ports:
      - "8004:8000"

  server-5:
    build: .
    container_name: server-5
    command: python server.py 8000
    ports:
      - "8005:8000"

  # --- CLIENT ---
  client:
    build: .
    container_name: client-1
    command: python client.py
    depends_on:
      - server-1
      - server-2
      - server-3
      - server-4
      - server-5
    environment:
      - MODE=DOCKER  # <--- This tells Python to use 'server-X' URLs