version: "3.8"

services:
  worker1:
    build: .
    container_name: worker1
    command: python server.py 50051
    ports:
      - "50051:50051"

  worker2:
    build: .
    container_name: worker2
    command: python server.py 50052
    ports:
      - "50052:50052"

  worker3:
    build: .
    container_name: worker3
    command: python server.py 50053
    ports:
      - "50053:50053"

  worker4:
    build: .
    container_name: worker4
    command: python server.py 50054
    ports:
      - "50054:50054"

  worker5:
    build: .
    container_name: worker5
    command: python server.py 50055
    ports:
      - "50055:50055"
client:
    build: .
    container_name: client
    command: ["python","client.py","distributed","worker1:50051,worker2:50052,worker3:50053,worker4:50054,worker5:50055"]
    depends_on:
      - worker1
      - worker2
      - worker3
      - worker4
      - worker5
