services:

  servicea:
    build: .
    container_name: servicea
    environment:
      - SERVICE_NAME=Service A
      - PORT=8001
      - NEXT_SERVICE=serviceb
      - NEXT_PORT=8002
      - IN_DOCKER=1
    ports:
      - "8001:8001"
    command: python serviceA/servicea.py

  serviceb:
    build: .
    container_name: serviceb
    environment:
      - SERVICE_NAME=Service B
      - PORT=8002
      - NEXT_SERVICE=servicec
      - NEXT_PORT=8003
      - IN_DOCKER=1
    ports:
      - "8002:8002"
    command: python serviceB/serviceb.py

  servicec:
    build: .
    container_name: servicec
    environment:
      - SERVICE_NAME=Service C
      - PORT=8003
      - NEXT_SERVICE=serviced
      - NEXT_PORT=8004
      - IN_DOCKER=1
    ports:
      - "8003:8003"
    command: python serviceC/servicec.py

  serviced:
    build: .
    container_name: serviced
    environment:
      - SERVICE_NAME=Service D
      - PORT=8004
      - NEXT_SERVICE=servicee
      - NEXT_PORT=8005
      - IN_DOCKER=1
    ports:
      - "8004:8004"
    command: python serviceD/serviced.py

  servicee:
    build: .
    container_name: servicee
    environment:
      - SERVICE_NAME=Service E
      - PORT=8005
      - IN_DOCKER=1
    ports:
      - "8005:8005"
    command: python serviceE/servicee.py

  client:
    build: .
    container_name: client
    environment:
      - IN_DOCKER=1
    depends_on:
      - servicea
      - serviceb
      - servicec
      - serviced
      - servicee
    command: python client/client.py
